config/routes.rb
Dunamis::Application.routes.draw do

  resources :marcas do
    resources :productos_marcas do
      collection do
        get :create_remote
      end
    end
  end

  resources :usuarios

  resources :medio_organizaciones

  resources :productos_marcas

  resources :reportes_adjuntos

  resources :reportes

  resources :informes

  resources :actores

  resources :adjuntos do
    collection do
      get :eliminar_total_adjuntos
      get :full_index
      get :descargar
      get :desechar_inutilizados
    end
  end

  resources :organizaciones

  resources :estructuras_medios

  resources :medios do
    collection do
      get :index_impresos
    end
  end

  resources :claves

  resources :productos do
    resources :productos_marcas
  end

  resources :entornos

  resources :toldas

  resources :ambitos

  resources :clases

  resources :externas

  resources :internas

  resources :tipo_especializaciones

  resources :especializaciones_medio

  resources :tipos_medios

  get "home/index"

  root :to => 'home#index'

  match ':controller(/:action(/:id))(.:format)'
end

app/models/entorno.rb
class Entorno < ActiveRecord::Base
  attr_accessible :nombre


  has_many :claves
  accepts_nested_attributes_for :claves

  has_many :organizaciones
  accepts_nested_attributes_for :organizaciones
end

app/controllers/entornos_controller.rb
# encoding: UTF-8
class EntornosController < ApplicationController
  # GET /entornos
  # GET /entornos.json

  before_filter :filtro_logueado
  before_filter :filtro_logueado_dunamis


  def index
    @entornos = Entorno.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @entornos }
    end
  end

  # GET /entornos/1
  # GET /entornos/1.json
  def show
    @entorno = Entorno.find(params[:id])
    @clave = Clave.new
    @clave.entorno_id = @entorno.id
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @entorno }
    end
  end

  # GET /entornos/new
  # GET /entornos/new.json
  def new
    @entorno = Entorno.new
    @entorno.organizacion_id = params[:organizacion_id] if params[:organizacion_id]

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @entorno }
    end
  end

  # GET /entornos/1/edit
  def edit
    @entorno = Entorno.find(params[:id])
    @entorno.organizacion_id = params[:organizacion_id] if params[:organizacion_id]
    
  end

  # POST /entornos
  # POST /entornos.json
  def create
    @entorno = Entorno.new(params[:entorno])

    respond_to do |format|
      if @entorno.save
        format.html { redirect_to @entorno, notice: 'Actividad Económica registrada con éxito.' }
        format.json { render json: @entorno, status: :created, location: @entorno }
      else
        format.html { render action: "new" }
        format.json { render json: @entorno.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /entornos/1
  # PUT /entornos/1.json
  def update
    @entorno = Entorno.find(params[:id])

    respond_to do |format|
      if @entorno.update_attributes(params[:entorno])
        format.html { redirect_to @entorno, notice: 'Actividad Económica actualizada con éxito.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @entorno.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /entornos/1
  # DELETE /entornos/1.json
  def destroy
    @entorno = Entorno.find(params[:id])
    @entorno.destroy

    respond_to do |format|
      format.html { redirect_to entornos_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/entornos_helper.rb
module EntornosHelper
end

app/views/entornos/_form.html.erb
<%= form_for @entorno, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label :nombre, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :nombre, :class => 'text_field' %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                entornos_path, :class => 'btn' %>
  </div>
<% end %>

app/views/entornos/edit.html.erb
<%- model_class = Entorno -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/entornos/index.html.erb
<%- model_class = Entorno -%>
<div class="page-header">
  <h1>Actividades Economicas
    <%= link_to 'Nueva',
            new_entorno_path,
            :class => 'btn btn-primary' %>

  </h1>
</div>

<%- @table_name = 'entornos'%>
<%= render partial: '/layouts/filtro_tabla' %>

<table class="table table-striped table-hover table-condensed" id="entornos">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:nombre) %></th>
      <th>Palabras Claves </th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @entornos.each do |entorno| %>
      <tr>
        <td><%= link_to entorno.nombre, entorno_path(entorno) %></td>
        <td style="text-align: justify;"><%= entorno.claves.collect{|c| c.valor}.join(",") %></td>
        <td>

          <b class='tooltip-btn' data_toggle='tooltip' title='Editar Entorno'>
            <%= link_to edit_entorno_path(entorno), { :role => 'button', :class => 'btn btn-info btn-mini'} do %>
              <%= content_tag(:i, "", class: "icon-edit icon-white") %>
            <% end %>
          </b>  

          <b class='tooltip-btn' data_toggle='tooltip' title='Eliminar Entorno' >
            <%= link_to entorno_path(entorno), { :role => 'button', :class => 'btn btn-danger btn-mini', :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => '¿Estas seguro de esta acción?')) }} do %>
              <%= content_tag(:i, "", class: "icon-trash icon-white") %>
            <% end %>
          </b>

        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to 'Nueva',
            new_entorno_path,
            :class => 'btn btn-primary' %>

app/views/entornos/new.html.erb
<%- model_class = Entorno -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/entornos/show.html.erb
<%- model_class = Entorno -%>
<div class="page-header">
  <h2>Actividad Económica: </h2>

<div class="form-actions">
  <h3><%= @entorno.nombre %> </h3>
    <%= link_to t('.back', :default => t("helpers.links.back")), entornos_path, :class => 'btn' %>
    <b class='tooltip-btn' data_toggle='tooltip' title= "Editar" >
      <%= link_to "", {:href => edit_entorno_path(@entorno), :class => 'btn btn-info'}, { :role => 'button'} do %>
        <%= content_tag(:i, "", class: "icon-edit icon-white") %>
      <% end %>
    </b>
</div>


<ul class="nav nav-tabs" id="TabMedios">
  <li class="active"><a href="#claves">Palabras Claves</a></li>
  <li><a href="#organizaciones">Organizaciones</a></li>
</ul>

<div class="tab-content">

  <div class="active tab-pane" id="claves">
    <%- @claves = @entorno.claves.order('created_at DESC')%>
    <%= render file:'/claves/index', layouts: false %>

      <%= link_to 'Agregar' , "javascript:void(0)", onclick: "$('#nueva_clave').show(300); $(this).hide();", class: 'btn btn-primary' %>

      <div id="nueva_clave" style="display: none;">
        <h4>Agregar Clave:</h4>
        <%= render partial: '/claves/form' %>
      </div>

  </div>
  <div class="tab-pane" id="organizaciones">
    <%- @organizaciones = @entorno.organizaciones.order(['interna_id DESC','created_at DESC']) %>
    <%= render :file =>'/organizaciones/index', :layouts => false %>
    <%= link_to t('.new', :default => t("helpers.links.new")), "#{new_organizacion_path}?entorno_id=#{@entorno.id}", :class => 'btn btn-primary' %>
  </div>
</div>