config/routes.rb
Dunamis::Application.routes.draw do

  resources :marcas do
    resources :productos_marcas do
      collection do
        get :create_remote
      end
    end
  end

  resources :usuarios

  resources :medio_organizaciones

  resources :productos_marcas

  resources :reportes_adjuntos

  resources :reportes

  resources :informes

  resources :actores

  resources :adjuntos do
    collection do
      get :eliminar_total_adjuntos
      get :full_index
      get :descargar
      get :desechar_inutilizados
    end
  end

  resources :organizaciones

  resources :estructuras_medios

  resources :medios do
    collection do
      get :index_impresos
    end
  end

  resources :claves

  resources :productos do
    resources :productos_marcas
  end

  resources :entornos

  resources :toldas

  resources :ambitos

  resources :clases

  resources :externas

  resources :internas

  resources :tipo_especializaciones

  resources :especializaciones_medio

  resources :tipos_medios

  get "home/index"

  root :to => 'home#index'

  match ':controller(/:action(/:id))(.:format)'
end

app/controllers/home_controller.rb
# encoding: utf-8
class HomeController < ApplicationController
  def index    
  end
  
  def validar
    unless params[:usuario]
      flash[:alert] = "Debe Iniciar Sesión"
      redirect_to :action => "index"
      return
    end
    login = params[:usuario][:nombre_sesion]
    clave = params[:usuario][:contrasena]
    reset_session
    session[:usuario] = Usuario.autenticar(login,clave)
    if session[:usuario].nil?
      flash[:alert] = "Error en login o clave #{session[:usuario]}"
    else
      flash[:success] = "¡Bienvenido! #{session[:usuario].nombre}"
    end
    redirect_to :back
  end
  
  def cerrar_sesion
    reset_session
    flash[:success] = "Sesión Cerrada ¡Hasta pronto!"
    redirect_to :action => "index", :controller => "home"
  end
  
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
</br>
</br>
</br>
</br>
</br>
</br>
</br>
</br>
</br>
<div class="hero-unit" style= "text-align: center;">
  <h1>Burson Marsteller Venezuela</h1>
  <h2>Monitor de Medios</h2>
  <p>
  <% unless session[:usuario] %>
    <%= link_to "Entrar", "", :data => {:toggle => 'modal'}, :onclick => "return $('#iniciar_sesion').modal();", :style=> "text", :class => "btn btn-primary btn-large" %>
  <% else %>
    <%= link_to "Medios", medios_path, :class => "btn btn-primary btn-large" %>
    <%= link_to "Organizaciones", organizaciones_path, :class => "btn btn-primary btn-large" %>
    <%= link_to "Actores", actores_path, :class => "btn btn-primary btn-large" %>
  
  <% end %>
  </p>
</div>


						