config/routes.rb
Dunamis::Application.routes.draw do

  resources :marcas do
    resources :productos_marcas do
      collection do
        get :create_remote
      end
    end
  end

  resources :usuarios

  resources :medio_organizaciones

  resources :productos_marcas

  resources :reportes_adjuntos

  resources :reportes

  resources :informes

  resources :actores

  resources :adjuntos do
    collection do
      get :eliminar_total_adjuntos
      get :full_index
      get :descargar
      get :desechar_inutilizados
    end
  end

  resources :organizaciones

  resources :estructuras_medios

  resources :medios do
    collection do
      get :index_impresos
    end
  end

  resources :claves

  resources :productos do
    resources :productos_marcas
  end

  resources :entornos

  resources :toldas

  resources :ambitos

  resources :clases

  resources :externas

  resources :internas

  resources :tipo_especializaciones

  resources :especializaciones_medio

  resources :tipos_medios

  get "home/index"

  root :to => 'home#index'

  match ':controller(/:action(/:id))(.:format)'
end

app/models/marca.rb
class Marca < ActiveRecord::Base
  belongs_to :organizacion
  attr_accessible :nombre, :organizacion_id

  has_many :productos_marcas
  accepts_nested_attributes_for :productos_marcas

  has_and_belongs_to_many :productos, :join_table => "productos_marcas"
  accepts_nested_attributes_for :productos

  validates_presence_of :nombre, :organizacion_id
  validates :nombre, :uniqueness => true

end

app/controllers/marcas_controller.rb
# encoding: UTF-8
class MarcasController < ApplicationController
  # GET /marcas
  # GET /marcas.json
  before_filter :filtro_logueado
  before_filter :filtro_logueado_admin

  def index
    @marcas = Marca.order('nombre ASC')
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @marcas }
    end
  end

  # GET /marcas/1
  # GET /marcas/1.json
  def show
    @marca = Marca.find(params[:id])
    @producto = Producto.new
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @marca }
    end
  end

  # GET /marcas/new
  # GET /marcas/new.json
  def new
    @marca = Marca.new
    @clientes = Organizacion.clientes
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @marca }
    end
  end

  # GET /marcas/1/edit
  def edit
    @marca = Marca.find(params[:id])
    @clientes = Organizacion.clientes
  end

  # POST /marcas
  # POST /marcas.json
  def create
    @marca = Marca.new(params[:marca])

    respond_to do |format|
      if @marca.save
        format.html { redirect_to @marca, notice: 'Marca registrada con éxito.' }
        format.json { render json: @marca, status: :created, location: @marca }
      else
#        @clientes = Organizacion.clientes
        format.html { render action: "new"}
        format.json { render json: @marca.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /marcas/1
  # PUT /marcas/1.json
  def update
    @marca = Marca.find(params[:id])

    respond_to do |format|
      if @marca.update_attributes(params[:marca])
        format.html { redirect_to @marca, notice: 'Marca actualizada con éxito.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @marca.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /marcas/1
  # DELETE /marcas/1.json
  def destroy
    @marca = Marca.find(params[:id])
    @marca.destroy

    respond_to do |format|
      format.html { redirect_to marcas_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/marcas_helper.rb
module MarcasHelper
end

app/views/marcas/_form.html.erb
<%= form_for @marca, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label :nombre, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :nombre, :class => 'text_field', :autofocus => true, :placeholder => "Nombre de la Marca", :required => true %>
    </div>
  </div>

  <%- if controller_name.eql? 'organizaciones' or @organizacion %>
    <%= f.hidden_field :organizacion_id%>
    <%= hidden_field_tag :organizacion, true %> 
  <% else %>
    <div class="control-group">
      <%= f.label :organizacion_id, :class => 'control-label' %>
      <div class="controls">
        <%= f.collection_select :organizacion_id, @clientes, :id, :razon_social, {:prompt => "Clientes", :required => true}, { :class => 'selects2 span3'} %>
        <%# f.number_field :organizacion_id, :class => 'number_field' %>
      </div>
    </div>
  <% end -%>
  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                organizacion_path(@marca.organizacion), :class => 'btn' %>
  </div>
<% end %>

app/views/marcas/edit.html.erb
<%- model_class = Marca -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/marcas/index.html.erb
<%- model_class = Marca -%>
<%- if controller_name.eql? 'marcas' %>
  <div class="page-header">
    <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %>
      <%= link_to t('.new', :default => t("helpers.links.new")),
              new_marca_path,
              :class => 'btn btn-primary' %>
    </h1>
  </div>
<% end -%>  

<%- @table_name = 'marcas'%>
<%= render partial: '/layouts/filtro_tabla' %>

<table class="table table-striped table-hover table-condensed" id="marcas">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:nombre) %></th>
      <%- unless controller_name.eql? 'organizaciones' %>
        <th><%= model_class.human_attribute_name(:organizacion_id) %></th>
      <% end -%>
      <th style="width: 50%;">Productos</th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @marcas.each do |marca| %>
      <tr>
        <td><%= link_to marca.id, marca_path(marca) %></td>
        <td><%= marca.nombre %></td>
        <%- unless controller_name.eql? 'organizaciones' %>
          <td><%= marca.organizacion.razon_social %></td>
        <% end -%>
        <td><%= marca.productos.collect{|c| c.nombre}.join(",") %></td>
        <td>


          <%- edit_marca_path_temp = edit_marca_path(marca) %>
          <%- edit_marca_path_temp += "?organizacion_id=#{marca.organizacion_id}" if controller_name.eql? 'organizaciones' %>

          <b class='tooltip-btn' data_toggle='tooltip' title='Editar marca' >
            <%= link_to edit_marca_path_temp, { :role => 'button', :class => 'btn btn-info btn-mini'} do %>
              <%= content_tag(:i, "", class: "icon-edit icon-white") %>
            <% end %>
          </b>  

          <%- marca_path_temp = marca_path(marca) %>
          <%- marca_path_temp += "?organizacion=#{marca.organizacion_id}" if controller_name.eql? 'organizaciones' %>

          <b class='tooltip-btn' data_toggle='tooltip' title='Eliminar marca' >
            <%= link_to marca_path_temp, { :role => 'button', :class => 'btn btn-danger btn-mini', :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => '¿Estas seguro de esta acción?')) }} do %>
              <%= content_tag(:i, "", class: "icon-trash icon-white") %>
            <% end %>
          </b>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%- if controller_name.eql? 'marcas' %>

  <%= link_to t('.new', :default => t("helpers.links.new")),
            new_marca_path,
            :class => 'btn btn-primary' %>
<% end -%>

app/views/marcas/new.html.erb
<%- model_class = Marca -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/marcas/show.html.erb
<%- model_class = Marca -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:nombre) %>:</strong></dt>
  <dd><%= @marca.nombre %></dd>
  <dt><strong><%= model_class.human_attribute_name(:organizacion_id) %>:</strong></dt>
  <dd><%= @marca.organizacion.razon_social %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              organizacion_path(@marca.organizacion), :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_marca_path(@marca), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              marca_path(@marca),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>


<div class='well well-small'>

  <%-@productos = @marca.productos%>

  <% if @productos.count > 0 %>
    <h3>Productos</h3>
      <%= render file: '/productos/index', :layouts => false %>
  <% end %>
  <%= link_to 'Agregar' , "javascript:void(0)", onclick: "$('#nuevo_producto').show(300); $(this).hide();", class: 'btn btn-primary' %>

  <div id="nuevo_producto" style="display: none;">

    <%= form_tag({:controller => 'productos_marcas', :action => 'create'}, {:remote => true}) do |f| %>

      <div class="control-group">
        <div class="controls">
          <h6>

          <%= hidden_field_tag 'producto_marca[marca_id]', @marca.id %>

          <%= select_tag "producto_marca[producto_id]", options_from_collection_for_select(Producto.all, :id, :nombre, :required => true), { :class => 'selects2 span3', :prompt => "Productos"} %>
          |
          <%= submit_tag 'Asociar Producto', :onclick => 'location.reload();', :class => 'btn btn-small btn-primary' %>
          </h6>
        </div>
      </div>
    <% end %>

  </div>
</div>