config/routes.rb
Dunamis::Application.routes.draw do

  resources :marcas do
    resources :productos_marcas do
      collection do
        get :create_remote
      end
    end
  end

  resources :usuarios

  resources :medio_organizaciones

  resources :productos_marcas

  resources :reportes_adjuntos

  resources :reportes

  resources :informes

  resources :actores

  resources :adjuntos do
    collection do
      get :eliminar_total_adjuntos
      get :full_index
      get :descargar
      get :desechar_inutilizados
    end
  end

  resources :organizaciones

  resources :estructuras_medios

  resources :medios do
    collection do
      get :index_impresos
    end
  end

  resources :claves

  resources :productos do
    resources :productos_marcas
  end

  resources :entornos

  resources :toldas

  resources :ambitos

  resources :clases

  resources :externas

  resources :internas

  resources :tipo_especializaciones

  resources :especializaciones_medio

  resources :tipos_medios

  get "home/index"

  root :to => 'home#index'

  match ':controller(/:action(/:id))(.:format)'
end

app/models/producto.rb
class Producto < ActiveRecord::Base
  attr_accessible :descripcion, :nombre

  has_and_belongs_to_many :marcas, :join_table => "productos_marcas"
  accepts_nested_attributes_for :marcas

  validates_presence_of :nombre
  validates :nombre, :uniqueness => true

  def descripcion_completa
  	aux = "#{nombre}"
  	aux += " - #{descripcion}" if descripcion
  	return aux
  end
end

app/controllers/productos_controller.rb
# encoding: UTF-8
class ProductosController < ApplicationController
  # GET /productos
  # GET /productos.json
  before_filter :filtro_logueado
  before_filter :filtro_logueado_admin


  def index
    @productos = Producto.order('created_at DESC')

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @productos }
    end
  end

  # GET /productos/1
  # GET /productos/1.json
  def show
    @producto = Producto.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @producto }
    end
  end

  # GET /productos/new
  # GET /productos/new.json
  def new
    @producto = Producto.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @producto }
    end
  end

  # GET /productos/1/edit
  def edit
    @producto = Producto.find(params[:id])
  end

  # POST /productos
  # POST /productos.json


  def create

    producto = params[:producto]
    palabras = producto[:nombre].split(";")
    errores = ""
    total = 0
    palabras.each_with_index do |pa,i|
      producto[:nombre] = producto[:descripcion] = pa
      begin
        obj = Producto.new(producto)
        obj.save
        total += 1
      rescue Exception => e
        errores = "error en la palabra #{i+1}:< #{e} > |"
      end

    end
    mensaje = "Total de palabras: #{total}. "
      
    mensaje += "Errores: #{errores}" unless (errores.eql? '')

    redirect_to productos_path, notice: mensaje

  end

  # PUT /productos/1
  # PUT /productos/1.json
  def update
    @producto = Producto.find(params[:id])

    respond_to do |format|
      if @producto.update_attributes(params[:producto])
        format.html { redirect_to @producto, notice: 'Producto was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @producto.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /productos/1
  # DELETE /productos/1.json
  def destroy
    @producto = Producto.find(params[:id])
    @producto.destroy

    respond_to do |format|
      format.html { redirect_to productos_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/productos_helper.rb
module ProductosHelper
end

app/views/productos/_form.html.erb
<%= form_for @producto, :html => { :class => 'form-horizontal' } do |f| %>

<b class='tooltip-btn' data_toggle='tooltip' title="Incluye múltiples productos separados por ';'. En dicho caso la descripción será igual al nombre" >

  <div class="control-group">
    <%= f.label :nombre, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_area :nombre, :class => 'text_field', :size => '5x2', :autofocus => true, :placeholder => "Chocolate;Café;Cacao", :required => true %>

    </div>
  </div>
</b>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                productos_path, :class => 'btn' %>
  </div>
<% end %>

app/views/productos/edit.html.erb
<%- model_class = Producto -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/productos/index.html.erb
<%- model_class = Producto -%>
<%- if controller_name.eql? 'productos' %>
  <div class="page-header">
    <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %>
      <%= link_to t('.new', :default => t("helpers.links.new")),
              new_producto_path,
              :class => 'btn btn-primary' %>
    </h1>
  </div>
<% end -%>
<%- @table_name = 'productos'%>
<%= render partial: '/layouts/filtro_tabla' %>


<table class="table table-striped table-hover table-condensed" id="productos">

  <tbody>
    <% @productos.each do |producto| %>
      <tr>
        <td><%= link_to producto.nombre, producto_path(producto) %></td>
        <td><%= producto.descripcion %></td>
        <td><%= producto.marcas.collect{|c| c.nombre}.join(",") %></td>
        <%- if controller_name.eql? 'productos' %>
          <td>
            <%= link_to t('.edit', :default => t("helpers.links.edit")),
                        edit_producto_path(producto), :class => 'btn btn-mini' %>
            <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                        producto_path(producto),
                        :method => :delete,
                        :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                        :class => 'btn btn-mini btn-danger' %>
          </td>
        <% end -%>

        <%- if controller_name.eql? 'marcas' %>
          <%- @producto_marca = ProductoMarca.where(marca_id: @marca.id, producto_id: producto.id).first %>
          <td>
            <b class='tooltip-btn' data_toggle='tooltip' title='Desasociar producto de esta marca' >
              <%= link_to producto_marca_path(@producto_marca), { :role => 'button', :class => 'btn btn-danger btn-mini', :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => '¿Estas seguro de esta acción?')) }} do %>
                <%= content_tag(:i, "", class: "icon-remove icon-white") %>
              <% end %>
            </b>


          </td>
        <% end -%> 
      </tr>
    <% end %>
  </tbody>
</table>
<%- if controller_name.eql? 'productos' %>
  <%= link_to t('.new', :default => t("helpers.links.new")),
            new_producto_path,
            :class => 'btn btn-primary' %>
<% end -%>

app/views/productos/new.html.erb
<%- model_class = Producto -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/productos/show.html.erb
<%- model_class = Producto -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:nombre) %>:</strong></dt>
  <dd><%= @producto.nombre %></dd>
  <dt><strong><%= model_class.human_attribute_name(:descripcion) %>:</strong></dt>
  <dd><%= @producto.descripcion %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              productos_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_producto_path(@producto), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              producto_path(@producto),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>